# Generated by Django 6.0 on 2025-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('buy_rate', models.FloatField()),
                ('sell_rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
